---
- name: resolve platform specific vars
  include_vars: '{{item}}'
  with_first_found:
    - files:
        - '{{ansible_distribution}}-{{ansible_distribution_release}}.yml'
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
      skip: true
      paths:
        - '{{role_path}}/vars'

- name: download...
  become: yes
  become_user: root
  get_url:
    url: '{{gr_tgz_url}}'
    dest: /tmp/{{gr_tgz}}
    checksum: '{{gr_checksum}}'
    mode: 0644

- name: create install subdir...
  become: yes
  become_user: root
  file:
    path: '{{gr_install_subdir}}'
    mode: 0755
    state: directory

- name: unarchive...
  become: yes
  become_user: root
  unarchive:
    remote_src: yes
    src: /tmp/{{gr_tgz}}
    dest: '{{gr_install_subdir}}'
    creates: '{{gr_install_subdir}}/github-release'

- name: link...
  become: yes
  become_user: root
  file:
    src: '{{gr_install_subdir}}/github-release'
    dest: '{{gr_install_dir}}/github-release'
    state: link
